### PR TITLE
074 hide unavailable information on page

### LINKED ISSUE #74: Hide unavailable information on page
Create conditions in HTML code to display certain information about restaurants based on its value. When the user location is not chosen, 'Distance' and 'Time' texts should not be generated in the restaurant card. If vegan/vegetarian/gluten free options are not available in the restaurant - the same rule should apply.

### PR DESCRIPTION
**Pull request by ya-iris**
There have been created conditions for showing the rows from the restaurant data set.
The html structure for distance and time data is only created under the condition this data is present in the data set. In case the users have not specified their location, nothing appears then.

The same result is implemented for dietary options. In this case, HTML depends on values of these fields and HTML structure is only initiated in case of positive value 1.

The phone numbers fields as well are shown only in case there values are not 0

For credit_card and takeaway fields HTML structure is  always created but its contents depend on the negative or positive value of these fields.

In addition, in case the user has applied different filters for the combination which no restaurants have been found, a text informing about this outcome is created in the place of restaurant cards

### CODE REVIEW

**Comment by ilyassakhanov** [comment]
There is a problem with this pull request. Described at #118.

**Review by ilyassakhanov — APPROVED** [review]
Works good, nice improovement

**Review by riccardosl — APPROVED** [review]
Thank you Irina!
I tested Burger + Vegan = no restaurants found.

**Comment by ya-iris** [comment]
> Thank you Irina!
> I tested Burger + Vegan = no restaurants found.

Hope this won't happen often with full database)

**Pull request merged**
