### PR TITLE
069 partial phone numbers

### LINKED ISSUE #69: Partial phone numbers in MySQL
After running Zomato API script MySQL database rows  phone_num1 and phone_num2 doesn't have a full phone number, only one symbol from that number.
How to see the bug:
* Log into your database
* Type "SELECT phone_num1, phone_num2 FROM restaurant;"

### PR DESCRIPTION
**Pull request by ya-iris**
The string with phone numbers from extracted data is converted into a list.  The save_phones function then saves the first one or two numbers if they exist in the phones_list. It's elements are inserted in the database

### CODE REVIEW

**Comment by ilyassakhanov** [comment]
Line 10 in zomato_api_without_location_details.py has wrong indentation

**Comment by ya-iris** [comment]
> Line 10 in zomato_api_without_location_details.py has wrong indentation

Fixed

**Comment by ilyassakhanov** [comment]
Cannot review since my git has gone insane and does weird stuff

**Review by riccardosl — COMMENTED** [review]
Thank you for solving this!
I tried to test however I reached the API limit.

**Review by ilyassakhanov — APPROVED** [review]
Works, approving.

**Pull request merged**
