### PR TITLE
021 fav and like

### LINKED ISSUE #21: Fav and like
Developing backend to store and delete user's favorites and providing frontend utilities (like buttons) for this purpose

### PR DESCRIPTION
**Pull request by ya-iris**
In app.py the like_and_unlike function is created outside of the the route and is called inside the route function in case the request method is POST - so the button is clicked. Through the POST method the restaurant id is passed from the clicked like button to the function. It is then checked whether this restaurant has been liked - whether this restaurant's id is together with the current user's id in the restaurant_user table. If it is, then the click on the button leads to deleting the restaurant from favourites, otherwise, it is added to the junction table with favourites. 

The check_liked_restaurants function returns a list of liked restaurants' ids of the current user. This list is then passed to the template where it is used to define the like button appearance based on the presence of the restaurant in this list.

The like button appearance depends on the set conditions. In case the restaurant id(which is the element with index 0 in the restaurant data set) is in the list of liked restaurants' ids, the button is given the appearance of a filled star, otherwise - an empty star. For this purpose, svg and sprite are used. After the button has been clicked, the page is reloaded to update the list of liked restaurants' ids, so the button image is updated based on it

The route name has been changed to /home for easier identification, for example, when addressing it in JavaScript file. It is a convenient way of identification of routes after routes /login and /signup are added to the application

The favourites.js file is responsible for sending data about like buttons being clicked to the application and also for reloading the page in order to update appearance of the buttons.
In this file, line 5, the link used is for local server, so for production it should be changed from      'http://127.0.0.1:5000/home' to 'https://easyeats.live/home'

To test if it is working, check the restaurant_user table after each click. New rows will either appear or disappear there. You can change the id of the current user in the current_user variable in the beginning of the home() function

### CODE REVIEW

**Comment by ilyassakhanov** [comment]
You forgot to link an issue

**Comment by ilyassakhanov** [comment]
This looks great, but without login, none of this will work.

**Comment by ilyassakhanov** [comment]
Also, you are talking about changing the link but not saying where should it be changed

**Comment by ya-iris** [comment]
> Also, you are talking about changing the link but not saying where should it be changed

Yeah, I mentioned the js file there, but forgot to specify the line. Have updated it

**Comment by ya-iris** [comment]
> This looks great, but without login, none of this will work.

Don't worry, it'll be on github ASAP

**Comment by ya-iris** [comment]
> This looks great, but without login, none of this will work.

And again, this version here is already working, but with the user id specified and manually in the beginning of the home() function

**Review by riccardosl — APPROVED** [review]
Thank you, tested and working

mysql> select * from restaurant_user;
+---------------+---------+
| restaurant_id | user_id |
+---------------+---------+
|      16506006 |       0 |
|      16507029 |       0 |
+---------------+---------+
2 rows in set (0.00 sec)

**Review by ilyassakhanov — APPROVED** [review]
Liking algorithm works

**Review by Slemanof — APPROVED** [review]
It works, thank you Irina

**Pull request merged**
