### PR TITLE
062 website template supported by backend

### LINKED ISSUE #62: Website template supported by backend
The frontend part of the application ready connected to backend

### PR DESCRIPTION
**Pull request by ya-iris**
This branch contains frontend files and backend files for the Flask application. Frontend files include HTML file, CSS file, JavaScript files and images and are connected to the Python file with the Flask application which implements collection of user's chosen filters and executes MySQL queries based on the fetched information

### CODE REVIEW

**Review by ilyassakhanov — APPROVED** [review]
Great work! Looks nice

**Review by riccardosl — COMMENTED** [review]
Hi, thank you. Flask is running for me

**Review by ilyassakhanov — APPROVED** [review]
12/10

**Review by riccardosl — COMMENTED** [review]
seems ok to me, thank you

**Comment by ilyassakhanov** [comment]
> seems ok to me, thank you
@riccardosl 
If you want to approve the merge, please click on "Approve merge", not "Comment"

**Review by riccardosl — APPROVED** [review]
seems ok to me, thank you

**Review by riccardosl — APPROVED** [review]
approving

**Pull request merged**
