### PR TITLE
Frontend with implemented backend

### LINKED ISSUE #62: Website template supported by backend
The frontend part of the application ready connected to backend

### PR DESCRIPTION
**Pull request by ya-iris**
Implementation of the web page with the MySQL functionality behind it - making queries from the page to the database and retrieving restaurant records from it to HTML

### CODE REVIEW

**Review by Slemanof — APPROVED** [review]
Great job Irina, approved.

**Comment by ilyassakhanov** [comment]
Would be nice to have directories and files named without whitespaces. Later in this project, this change can save us time.

**Comment by ya-iris** [comment]
> Would be nice to have directories and files named without whitespaces. Later in this project, this change can save us time.

You're right, I'll make changes

**Comment by ilyassakhanov** [comment]
Currently, I am having problems with launching this script. Would be nice to have a list of prerequisites(i.e requirements.txt)

**Comment by ilyassakhanov** [comment]
Looks like you're using a different SQL script for your database and it stores data differently. Can't test it since you didn't share your new version of the script for storing data.

**Comment by ya-iris** [comment]
There have been accidentally added redundant files from the branch in this pull request. Thus, I am closing it and creating a new one with the needed folder only

**Comment by svarnypetr** [comment]
> There have been accidentally added redundant files from the branch in this pull request. Thus, I am closing it and creating a new one with the needed folder only

@irinakulinich3712  Please link/mention the new pull request.

**Pull request closed without merging**
