### PR TITLE
017 recommendations (backup version)

### LINKED ISSUE #17: Recommendations
Recommendation system development based on restaurants liked by the user and added to the restaurant_user junction table by their id corresponding to the user's id

### LINKED ISSUE #112: Typos in the "Sort by" dropdown
The "Sort by" dropdown has a typo if word from. It is spelt as "fom".

**To Reproduce**
Go to the "Sort by" dropdown.

### LINKED ISSUE #118: Small amount of recomendations
If you have liked some specific combination of restaurants you could get a very small amount of restaurants or none

**To Reproduce**
Leave a lot of likes in different restaurants with different cuisines

### PR DESCRIPTION
**Pull request by ya-iris**
The recommendation function is declared outside of route and is called in the route function in case the user hasn't chosen any filters and the query string is empty. If so, it is checked if the user has liked any restaurants - if the user_id is in the restaurant_user junction table, containing user ids and ids of the liked restaurants. If no restaurants have been liked, so the user_id is absent in the junction table, then all restaurants are fetched to the page according to descending order of their ratings. Else, up to 3 most frequent cuisines among the liked restaurants are identified and the most frequent values of dietary options and price range. Then, restaurants matching these criterias are found and fetched to the page. Once the user has applied any filters, restaurants based on them are fetched instead.

Further, as the login function is added, it will automatically pass id of the current user in the current_user variable. For now it is set to 0 and you can set it manually based on which user from the database you want to work with. Use the updated database structure for this purpose. Currently you need to add users manually to the user table. Same applies to the table with liked restaurants - restaurant_user: insert user ids along with restaurant ids from the restaurant table. 

Closes #17

### CODE REVIEW

**Comment by ilyassakhanov** [comment]
It looks like we cannot log into as any user. That means we don't get any recommendations

**Comment by ya-iris** [comment]
> It looks like we cannot log into as any user. That means we don't get any recommendations
Of course, you don't, there is no login and signup here...I mention that in the description

**Comment by ya-iris** [comment]
> It looks like we cannot log into as any user. That means we don't get any recommendations

And yes, you do get recommendations, you should use a specific user id for that, again, I wrote that in the description. You need to specify id of the user(existing in the database) by hand before the recommendations function is called in the route. Currently the id is set to 0. As login is added, the user id will be passed automatically from jwt in the cookies

**Review by riccardosl — APPROVED** [review]
Thank you Irina, 
I tested that the app will recommend me same cuisine type. If clicked like to Asian and cafe'. it will show first those types of restaurants. Perfect

**Review by ilyassakhanov — APPROVED** [review]
Works fine

**Review by Slemanof — APPROVED** [review]
It works. Great!

**Pull request merged**
