### PR TITLE
095 flask login infrastructure

### LINKED ISSUE #95: Flask Login infrastructure
We have currently no user login capacity.

The user should be able to register and later on login. The data about the user are stored in the user database.

**Todo**:
- [x] Allow the user to login (i.e. check the database about the user login data and use them to authenticate the user.)
- [x] Allow the user to register (i.e. add new authentication data to the user database).
- [x] Track/keep the user logged in after login operation.
- [x] Add relevant buttons/UI features for login/register/logout.
- [x] Investigate/treat login behaviour in the case the user closes the window/tab/ends the session.

### LINKED ISSUE #111: Rating from high to low
On the website, sort option by default is set as "Rating from high to low". But it doesn't sort by the rating.

**To Reproduce**
Go to the our website. Watch the order of ratings

**Expected behaviour**
The restaurants should be ordered from high rating to low by default or empty field as default sort.

### LINKED ISSUE #121: Add instructions for password structure
It is inconvenient for the user to sign up if there is no clear instruction about what the password should consist of (Uppercase letters, digits and etc.) Thus, it is annoying to receive error messages about what the password must include every time you try to submit it

It will be comfortable for the user to have a small text underneath the password input in the signup form with description of all characters this field should include. The user will still get error messages after submission of password if these instructions haven't been followed

### LINKED ISSUE #122: Strict input validation
For security reasons it is better to allow only certain characters for user input fields. This should be implemented on server side

### PR DESCRIPTION
**Pull request by ya-iris**
There have been added 2 new templates: signup.html and login.html

The signup template includes 4 inputs for the user's name, email, password and its confirmation.. In addition there is a link to the login page in case the user already has registered. When the password is being entered, it is shadowed. It also has a set minimum and maximum length: 8 -20 characters. The email format is automatically validated in the page by checking if it includes @ and characters before and after this character.

The login form includes 2 inputs - for email and password. There is also a link to the signup page in case the user has not registered yet.
For both templates all fields are set to mandatory and the form can not be submitted without filling all of them.

There have been created 3 new routes in app.py (All routes are now in the same file, which is inconvenient. After this pull request is accepted, I will restructure the application and save routes in separate files)

/signup
In the route function user input from the signup form is received. For name and email fields escape_string is applied in order to escape special characters. The user input is validated first through checking if the password and confirmed password match. If they don't a message about it is send to the user. Otherwise, validation is taken to the next step - checking if the email is already in the database. If it is, again, the user receives a message about it in the page. If there is no such email in the database, the user can be added to it. For this case user password is hashed and then all credentials are added to the database. The user then gets a message about successful registration.

/login
This route needs to be an entry point to the application
In the route function users' credentials are received from the login form. escape_string is applied to email. First, it is checked if such email exists in the database. If it does not, the user receives an error message in the login page. Otherwise, the entered password is validated and compared with the one from the database - from the same record with the verified email. If passwords do not match - the user receives an error message. Otherwise, an access token is generated. It is linked to this user by setting the user's id from the database as identity. The token is set in the cookie which is set in the response object. Response is then send to the browser, to the protected route where the cookie with the token appears. In the jwt configuration in the beginning of the file the location for sending this cookie has been set to /home route which is supposed to be a protected route in the application and is only accessible with jwt token from cookies. Cookies here are by default httpOnly. They should also be configured to be secure(line 19), but this configuration can only be set to True in production mode for HTTPS connection. Here, in development mode, this configuration is now set to False. The life time of JWT has been set to 2 hours, after this period the token will expire. Cookies will only be available untill the browser is closed.

/logout
The users will be redirected to this route after they click the "Logout" button in the home page. The route function clears the cookies , so the protected route will not be accessible anymore

Protection of the /home route
@jwt_required is added before the route function. It checks for the jwt availability in the cookies. If there is no token, it has expired or there is no cookie, the content of the page will not be accessible.
If the token has been verified, the page is accessible.

Here the user identity is extracted from the token, which is the user's id. This id is then passed to the recommendations and like functions

If the access token is not valid for any reason (missing, expired, tampered with, etc) there is returned json in the format of {‘msg’: ‘why accessing endpoint failed’} along with an appropriate http status code (generally 401 or 422). With the jwt_manager loader functions it is possible to custmize this response.

expired_token_loader() is a function to call when an expired token accesses a protected endpoint

invalid_token_loader() is a function to call when an invalid token accesses a protected endpoint(for example, when cookie is missing)

After the token has expired/the user closed the browser and cookie has been deleted, if the user tries to reload the page or to perform any actions leading to this(searching for restaurants, liking restaurants) it will be considered an unauthorized access attempt or access attempt with an expired token. Once it is detected, the user will be redirected to the login page to get access again. For now there is no message about it appearing for the user before redirect. I will add this feature as soon as possible

In addition, I have created 3 JavaScript files

signup.js
This file receives values from the signup form after its submission. The password is validated and for each unfollowed rule (inclusion of uppercase letters/lowercase letters/digits/special characters) the user will receive an error message about the missing components. If the password structure has been validated, the credentials are received in the /signup route via POST method. If they have been varified there as well, the route function sends a response, which is caught in JS. Same happens when an error message is sent from the route function. According to this message, an alert appears in the top of the page, having a corresponding design and containing the message from backend.
If registration has passed successfully, the user is redirected to the login page.
In line 32 the url is used for localhost and should be changed in production mode

login.js
JS for login route works similar as for the signup route, yet does not perform validation. In case the response from the backend has been positive and the user has been verified, there is performed redirection to the home page. In case of errors with verifying the user in backend, alerts with the corresponding messages are evoked.
Again,  the url in line 6 should be changed in production mode

In /home page now there is also a Logout button under the header
After it has been clicked, the user is redirected to the logout route. There, in the backend, cookies are cleared and a response message is send. If it is positive {'logout':True}, then the user is redirected to the login page. This transition is smooth and fast, so the user is immediately taken to the /login route basically from /home

Both signup() and login() functions need better validation methods, so I will modify them. The issue for this already exists

### CODE REVIEW

**Comment by ilyassakhanov** [comment]
When you first log into the website, everything is ordered by the rating, but if you apply any filter like cuisine, the restaurants are not ordered by rating anymore yet you have selected ordering by rating

**Comment by ya-iris** [comment]
> When you first log into the website, everything is ordered by the rating, but if you apply any filter like cuisine, the restaurants are not ordered by rating anymore yet you have selected ordering by rating

When you first log in and you have no liked restaurants, you get top restaurants as recommended ones, I already explained that in description for my recommendations pull request. I have not selected ordering by rating, again, I explained that to you in the comment section of one of the recent pull requests. Instead, the first option from the sorting drop-down menu is visible, but it has not been selected. I am preparing an update for that, so that option won't be visible

**Comment by ya-iris** [comment]
I have updated the process of redirecting the user to login page in case the token/cookie is not valid anymore. If such case is detected, the home page contents are not available then, instead another template is rendered - redirect.html. There, the users are informed about their session ending and the need to verify their identity again. After a few moments the user is then redirected to login page. If they try to go back to home page without login - they will again get the same message and will be redirected back to login

**Comment by ya-iris** [comment]
Also, have made a new update on input validation both in signup and login functions, it is now controlled that certain input contains certain characters or/and has a specified structure, for example email field in signup()

**Comment by ya-iris** [comment]
Another update - instruction for the password structure is now available in the signup form

**Review by ilyassakhanov — APPROVED** [review]
That's a lot of work you've done. Great work!

**Review by Slemanof — APPROVED** [review]
Works perfectly, great job thank you <3

**Review by riccardosl — APPROVED** [review]
thank you Irina!

**Review by Stanley008 — APPROVED** [review]
A lot of work, get some sleep : )

**Pull request merged**
